root: true
env:
  browser: false
  node: true
  es2022: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
  - 'prettier'
rules:
  semi:
    - error
    - always
  '@typescript-eslint/prefer-namespace-keyword': 0
  '@typescript-eslint/no-namespace': 0
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/ban-ts-comment': 1
  '@typescript-eslint/no-unsafe-declaration-merging': off
  no-useless-escape: 0
  import/no-anonymous-default-export: 0
  no-console: 2
  no-extra-boolean-cast: 0
  no-async-promise-executor: 0
  prettier/prettier:
    - warn
