name: 'NPM Publish'

on:
  push:
    branches:
      - 'main'

jobs: 
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 21.4.0
          registry-url: "https://registry.npmjs.org"
          scope: "ben-merritt"
      - name: Bump Up Version
        run: |
          yarn
          yarn build
          npm config set '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'
          yarn publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

